name: Refresh GitHub Card Cache

on:
  schedule:
    - cron: '0 * * * *' # Runs automatically every hour
  workflow_dispatch: # Allows you to also trigger it manually via a button

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update Cache Buster Number
        run: |
          # Generates a random number to append to your card link
          RANDOM_NUM=$RANDOM
          sed -i -E "s|(://githubcard.com\?d=Ag76GRzI9rSa\&v=)[0-9]*|\1$RANDOM_NUM|g" README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add README.md
          git commit -m "chore: auto-refresh github card cache" || exit 0
          git push
